# This is a basic workflow to help you get started with Actions

name: IngressNginx

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Docker pull and push
        run: |
          docker pull k8s.gcr.io/ingress-nginx/controller:v1.0.4@sha256:545cff00370f28363dad31e3b59a94ba377854d3a11f18988f5f9e56841ef9ef
          docker pull k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660
          docker pull k8s.gcr.io/sig-storage/nfs-provisioner:v3.0.0
          docker pull k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.4

          docker tag k8s.gcr.io/ingress-nginx/controller:v1.0.4@sha256:545cff00370f28363dad31e3b59a94ba377854d3a11f18988f5f9e56841ef9ef ghcr.io/githubweidf/ingress-nginx/controller:v1.0.4
          docker tag k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660 ghcr.io/githubweidf/ingress-nginx/kube-webhook-certgen:v1.1.1
          docker tag k8s.gcr.io/sig-storage/nfs-provisioner:v3.0.0 ghcr.io/githubweidf/sig-storage/nfs-provisioner:v3.0.0
          docker tag k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.4 ghcr.io/githubweidf/kube-state-metrics/kube-state-metrics:v2.2.4

          docker push ghcr.io/githubweidf/ingress-nginx/controller:v1.0.4
          docker push ghcr.io/githubweidf/ingress-nginx/kube-webhook-certgen:v1.1.1
          docker push ghcr.io/githubweidf/sig-storage/nfs-provisioner:v3.0.0
          docker push ghcr.io/githubweidf/kube-state-metrics/kube-state-metrics:v2.2.4